config/routes.rb
Shoutbox::Application.routes.draw do
  
  resources :shouts, :only => [:new, :create, :index]
  

   root :to => "shouts#index"

end

app/models/shout.rb
class Shout < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :body
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def new
    @shout = Shout.new
  end
  
  def create
    @shout = Shout.new(params[:shout])
    if @shout.save
      flash[:notice] = "Thanks for shouting!"
      redirect_to shouts_url
    else
      render :new
    end
  end
  
  def index
    @shouts = Shout.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoutbox</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="flash">
	<% flash.each do |key, value| -%>
		<div id="flash_<%= key %>"><%=h value %></div>
	<% end -%>
</div>

<%= yield %>

<!-- <a href="http://localhost:3000/shouts">Index</a> -->

<%= link_to "Index" , shouts_path %>
<%= link_to "Add New Shout" , new_shout_path %>

</body>
</html>

app/views/shouts/index.html.erb
<% @shouts.each do |s| %>
	<ul>
		<li>
		<%= s.name %>
		</li>
		<li>
		<%= s.body%>
		</li>
	</ul>
<% end %>

app/views/shouts/new.html.erb
<%= form_for @shout do |form| %>
	<%= form.error_messages %>
	<%= form.label :name %>
	<%= form.text_field :name %>
	
	<%= form.label :body %>
	<%= form.text_area :body %>
	
	<%= form.submit %>
<% end %>